let Group = require('./group.js')
let Person = require('./person.js')
let Roster = require('./roster.js')
let Sorter = require('./groupSorter.js')
let ResultSet = require('./resultSet')

let roster = new Roster()
let sorter = new Sorter(roster)

let power = new Group('Power', 2, 3)
let knowledge = new Group('Knowledge', 2, 3)
let sexuality = new Group('Sexuality', 2, 3)
let subjectivity = new Group('Subjectivity', 2, 3)

sorter.addGroup(power)
sorter.addGroup(knowledge)
sorter.addGroup(sexuality)
sorter.addGroup(subjectivity)

let abby = new Person('Abby', [power, knowledge, subjectivity, sexuality])
let alex = new Person('Alex', [power, subjectivity, knowledge, sexuality])
let bob = new Person('Bob', [subjectivity, power, knowledge, sexuality])
let cass = new Person('Cass', [sexuality, subjectivity, knowledge, power])
let dan = new Person('Dan', [knowledge, sexuality, power, subjectivity])
let eric = new Person('Eric', [power, sexuality, subjectivity, knowledge])
let fan = new Person('Fan', [power, knowledge, sexuality, subjectivity])
let gary = new Person('Gary', [power, subjectivity, sexuality, knowledge])
let hank = new Person('Hank', [knowledge, power, subjectivity, sexuality])
let jess = new Person('Jess', [sexuality, power, subjectivity, knowledge])
let kate = new Person('Kate', [knowledge, power, subjectivity, sexuality])
let matt = new Person('Matt', [power, subjectivity, sexuality, knowledge])


roster.enroll(eric)
roster.enroll(abby)
roster.enroll(bob)
roster.enroll(cass)
roster.enroll(dan)
roster.enroll(hank)
roster.enroll(jess)
roster.enroll(kate)
roster.enroll(matt)
roster.enroll(alex)
roster.enroll(gary)
roster.enroll(fan)

let sets = new Array(10).fill(null)

sets.forEach((set, id) => {
  sorter.balanceFromTop()
  sets[id] = new ResultSet(sorter)
})
